//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatilleraWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        public int AbonoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public int UsuarioId { get; set; }
        public int PrestamoId { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
