//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatilleraWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multa
    {
        public int MultaId { get; set; }
        public decimal Monto { get; set; }
        public int TipoMultaId { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual TipoMulta TipoMulta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
